"""empty message

Revision ID: 0e555bae27dd
Revises: 
Create Date: 2019-11-20 23:27:44.359384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e555bae27dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('job_class', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('Enqueued', 'Started', 'Error', 'Executed'), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('result_link', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_model')
    # ### end Alembic commands ###
