"""empty message

Revision ID: 641b8fcf0d7a
Revises: 
Create Date: 2019-11-19 18:35:04.180624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641b8fcf0d7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('job_class', sa.String(length=200), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Enqueued', 'Started', 'Error', 'Executed'), server_default='Enqueued', nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('result_link', sa.String(length=2000), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_model')
    # ### end Alembic commands ###
